// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIgdE_v9K57XeJbvDeuoMv0Va18PVYWj0',
    appId: '1:334996566021:web:e1b7dd2c2e2ee4837eec6c',
    messagingSenderId: '334996566021',
    projectId: 'note-1ff0c',
    authDomain: 'note-1ff0c.firebaseapp.com',
    storageBucket: 'note-1ff0c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIpl96AGHFE8H9XyJBMjKtN0qASAgIF8g',
    appId: '1:334996566021:android:0383ba0b3c1a93027eec6c',
    messagingSenderId: '334996566021',
    projectId: 'note-1ff0c',
    storageBucket: 'note-1ff0c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNQoNzkKzRiaPIr9FcuiEeDennXhfddSQ',
    appId: '1:334996566021:ios:c39d303fa1c6b7cf7eec6c',
    messagingSenderId: '334996566021',
    projectId: 'note-1ff0c',
    storageBucket: 'note-1ff0c.firebasestorage.app',
    iosBundleId: 'com.example.notesecure',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNQoNzkKzRiaPIr9FcuiEeDennXhfddSQ',
    appId: '1:334996566021:ios:c39d303fa1c6b7cf7eec6c',
    messagingSenderId: '334996566021',
    projectId: 'note-1ff0c',
    storageBucket: 'note-1ff0c.firebasestorage.app',
    iosBundleId: 'com.example.notesecure',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIgdE_v9K57XeJbvDeuoMv0Va18PVYWj0',
    appId: '1:334996566021:web:8d0104359555bd337eec6c',
    messagingSenderId: '334996566021',
    projectId: 'note-1ff0c',
    authDomain: 'note-1ff0c.firebaseapp.com',
    storageBucket: 'note-1ff0c.firebasestorage.app',
  );
}
